// Package kafkatest provides a reusable Kafka test container for
// integration tests. It wraps testcontainers-go to manage a single-node
// Apache Kafka broker in KRaft mode, and exposes helpers for topic
// management, message production, and offset inspection.
//
// The package is intentionally placed under internal/ to prevent
// external consumers from depending on test infrastructure.
package kafkatest

import "fmt"

// Header is a Kafka message header (key-value pair).
type Header struct {
	Key   string
	Value []byte
}

// ProduceMessage defines a single message to publish to Kafka.
// All fields are optional except Value. When Key is nil, Kafka
// uses round-robin partition assignment.
type ProduceMessage struct {
	Key     []byte
	Value   []byte
	Headers []Header
}

// NewMessages creates count messages with sequential keys ("key-0",
// "key-1", ...) and values generated by valueFn. This is a convenience
// constructor for the common "produce N test messages" pattern.
func NewMessages(count int, valueFn func(i int) []byte) []ProduceMessage {
	msgs := make([]ProduceMessage, count)
	for i := range count {
		msgs[i] = ProduceMessage{
			Key:   []byte(fmt.Sprintf("key-%d", i%10)),
			Value: valueFn(i),
		}
	}
	return msgs
}
